//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_3_1_EvidencijaStudenata
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aktivnost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aktivnost()
        {
            this.AktivnostStudenta = new HashSet<AktivnostStudenta>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
        public double MaxBodovi { get; set; }
        public double UvjetPotpis { get; set; }
        public double UvjetOcjena { get; set; }
        public Nullable<System.DateTime> Pocetak { get; set; }
        public Nullable<System.DateTime> Kraj { get; set; }
        public string Opis { get; set; }
        public int TipAktivnostiId { get; set; }
    
        public virtual TipAktivnosti TipAktivnosti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AktivnostStudenta> AktivnostStudenta { get; set; }
    }
}
