//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_3_1_EvidencijaStudenata
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EvidencijaStudenataEntities : DbContext
    {
        public EvidencijaStudenataEntities()
            : base("name=EvidencijaStudenataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aktivnost> Aktivnost { get; set; }
        public virtual DbSet<AktivnostStudenta> AktivnostStudenta { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Tim> Tim { get; set; }
        public virtual DbSet<TipAktivnosti> TipAktivnosti { get; set; }
    }
}
